name: Counterpoint
favicon: null
layout_spectrum: 0.33858
typography_spectrum: 0.50986
title: Cloud Hosted Business Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#ffffff'
    - '#3bc1cc'
    - '#d2d2d3'
    - '#959595'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
